# . . . [autostart] . . . #

# {launch on boot} #

exec-once = hyprpaper # wallpaper
exec-once = waybar # status bar
exec-once = mako # notification daemon
exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 # authentication agent
exec-once = hypridle # lock trigger
