# . . . [input] . . . #

input {
    kb_layout = us, am # keyboard layouts
    kb_variant = , western # variants
    kb_model =
    kb_options = grp:alt_shift_toggle # switch layouts
    kb_rules =

    follow_mouse = 1 # window focus follows mouse

    sensitivity = 0 # mouse sensitivity
        
    touchpad {
        natural_scroll = false # scroll direction
        disable_while_typing = false # disable touchpad while keyboard in use or not
    }
}

# {gestures} #

gesture = 3, horizontal, workspace # three finger swipe = switch workspace

# {devices} #

device {
    name = synaptics-tm3276-022 # touchpad
    scroll_method = on_button_down # middle click and move trackpoint = scroll
    scroll_button = 274 # middle click
}

device {
    name = tpps/2-ibm-trackpoint # trackpoint
    scroll_method = on_button_down 
    scroll_button = 274
    natural_scroll = false
    middle_button_emulation = false
}

