# . . . [keybinds] . . . #

$mainMod = SUPER # windows key set as mainmod

bind = $mainMod, Return, exec, $terminal # windows + enter = terminal
bind = $mainMod, Q, killactive, # windows + Q = quit
bind = $mainMod, W, exec, $browser # windows + W = browser
bind = $mainMod, E, exec, $fileManager # windows + E = file manager
bind = $mainMod, L, exec, hyprlock # windows + L = lock screen
bind = $mainMod, V, togglefloating, # windows + V = make window float
bind = $mainMod, Space, exec, pkill wofi || wofi --show drun # windows + space = app launcher
bind = $mainMod, P, pseudo, # pseudo tile toggle
bind = $mainMod, J, layoutmsg, togglesplit # tile layout switch

# scratchpad #

bind = $mainMod, S, togglespecialworkspace, board # open 
bind = $mainMod SHIFT, S, movetoworkspace, special:board # move to

bind = , Print, exec, grim ~/Pictures/screenshots/$(date +%Y-%m-%d_%H-%M-%S).png # full screenshot
bind = SHIFT, Print, exec, grim -g "$(slurp)" ~/Pictures/screenshots/$(date +%Y-%m-%d_%H-%M-%S).png # region screenshot

bind = $mainMod, left, movefocus, l # focus switch left
bind = $mainMod, right, movefocus, r # focus switch right
bind = $mainMod, up, movefocus, u # focus switch up
bind = $mainMod, down, movefocus, d # focus switch down

# windows + number = switch to that workspace

bind = $mainMod, 1, workspace, name:codex
bind = $mainMod, 2, workspace, name:study
bind = $mainMod, 3, workspace, name:commune
bind = $mainMod, 4, workspace, name:archive
bind = $mainMod, 5, workspace, name:profane
bind = $mainMod, 6, workspace, 6
bind = $mainMod, 7, workspace, 7
bind = $mainMod, 8, workspace, 8
bind = $mainMod, 9, workspace, 9
bind = $mainMod, 0, workspace, 10

# windows + shift + number = move focused window to that workspace

bind = $mainMod SHIFT, 1, movetoworkspace, name:codex
bind = $mainMod SHIFT, 2, movetoworkspace, name:study
bind = $mainMod SHIFT, 3, movetoworkspace, name:commune
bind = $mainMod SHIFT, 4, movetoworkspace, name:archive
bind = $mainMod SHIFT, 5, movetoworkspace, name:profane
bind = $mainMod SHIFT, 6, movetoworkspace, 6
bind = $mainMod SHIFT, 7, movetoworkspace, 7
bind = $mainMod SHIFT, 8, movetoworkspace, 8
bind = $mainMod SHIFT, 9, movetoworkspace, 9
bind = $mainMod SHIFT, 0, movetoworkspace, 10

bindm = $mainMod, mouse:272, movewindow # windows + click drag = move window
bindm = $mainMod, mouse:273, resizewindow # windows + right click drag = resize window

bindel = ,XF86AudioRaiseVolume, exec, wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ 5%+
bindel = ,XF86AudioLowerVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-
bindel = ,XF86AudioMute, exec, wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle
bindel = ,XF86AudioMicMute, exec, wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle
bindel = ,XF86MonBrightnessUp, exec, brightnessctl -e4 -n2 set 5%+
bindel = ,XF86MonBrightnessDown, exec, brightnessctl -e4 -n2 set 5%-

bindl = , XF86AudioNext, exec, playerctl next
bindl = , XF86AudioPause, exec, playerctl play-pause
bindl = , XF86AudioPlay, exec, playerctl play-pause
bindl = , XF86AudioPrev, exec, playerctl previous
