# . . . [vibe] . . . #

# {general} #

general {
    gaps_in = 4 # gap between windows
    gaps_out = 10 # gap between windows and screen edges

    border_size = 2 # window border thickness

    col.active_border = rgba(cba6f7ee) rgba(9a85c7ee) 45deg # focused window border
    col.inactive_border = rgba(2a1f3daa) # unfocused window border

    resize_on_border = false # drag to resize

    allow_tearing = false # screen tearing prevention

    layout = dwindle # tiling algorithm
}

# {decoration} #

decoration { 
    rounding = 0 # window corner curve radius
    rounding_power = 1 # window corner curve shape

    active_opacity = 1.0 # focused window transparency
    inactive_opacity = 0.95 # unfocused window transparency

    shadow {
        enabled = false # drop shadows
    }

    blur {
        enabled = false # background blur
    }
}

# {animations} #

animations {
    enabled = yes # toggle 

    #        NAME,           X0,   Y0,   X1,   Y1
    bezier = easeOutQuint,   0.23, 1,    0.32, 1
    bezier = easeInOutCubic, 0.65, 0.05, 0.36, 1
    bezier = linear,         0,    0,    1,    1
    bezier = almostLinear,   0.5,  0.5,  0.75, 1
    bezier = quick,          0.15, 0,    0.1,  1

    #           NAME,          ONOFF, SPEED, CURVE,        [STYLE]
    animation = global,        1,     6,     default
    animation = border,        1,     5.39,  easeOutQuint
    animation = windows,       1,     3,     easeOutQuint
    animation = windowsIn,     1,     4.1,   easeOutQuint, popin 87%
    animation = windowsOut,    1,     1.49,  linear,       popin 87%
    animation = fadeIn,        1,     1.73,  almostLinear
    animation = fadeOut,       1,     1.46,  almostLinear
    animation = fade,          1,     2,     linear
    animation = layers,        1,     3.81,  easeOutQuint
    animation = layersIn,      1,     4,     easeOutQuint, fade
    animation = layersOut,     1,     1.5,   linear,       fade
    animation = fadeLayersIn,  1,     1.79,  almostLinear
    animation = fadeLayersOut, 1,     1.39,  almostLinear
    animation = workspaces,    1,     2,     linear
    animation = workspacesIn,  1,     1.21,  almostLinear, fade
    animation = workspacesOut, 1,     0.5,   almostLinear, fade
    animation = zoomFactor,    1,     7,     quick
}

# {dwindle} #

dwindle {
    pseudotile = true #  
    preserve_split = true # closing a window doesn't rearrange the ones still open
}

# {misc} #

misc {
    force_default_wallpaper = 0 # set to 0 or 1 to disable the anime mascot wallpapers
    disable_hyprland_logo = true # 
}
