# . . . [workspaces] . . . #

workspace = name:codex, monitor:eDP-1, default:true
workspace = name:study, monitor:eDP-1
workspace = name:commune, monitor:eDP-1
workspace = name:archive, monitor:eDP-1
workspace = name:profane, monitor:eDP-1
